version = 1

test_patterns = [
  "MouseKitTests/**"
]

[[analyzers]]
name = "swift"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
  
[[transformers]]
name = "swift-format"
enabled = true
